version: '3.8'

services:
  db:
    image: postgres:15.3-alpine
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes: 
      - db:/var/lib/postgresql/data
  web:
    build:
      context: .
    depends_on: 
      - db
    ports:
      - 8001:8000
    env_file:
      - .env
volumes:
  db:
    driver: local