# Generated by Django 4.2.1 on 2023-05-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.BooleanField()),
                ('cigs_per_day', models.IntegerField()),
                ('bp_meds', models.BooleanField()),
                ('prevalent_stroke', models.BooleanField()),
                ('prevalent_hyp', models.BooleanField()),
                ('diabetes', models.BooleanField()),
                ('tot_chol', models.IntegerField()),
                ('sys_bp', models.IntegerField()),
                ('dia_bp', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('glucose', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='predictionmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
